### ISSUE TITLE
only appears to be working in root folder

### ISSUE THREAD

**Issue by justinphebey** [gdi3d/js-hmr-osx-docker-helper#1]
Hi

I tried using this as I'd like to get devcontainers to work as they should in vscode.

I followed the instructions having set up a basic devcontainer based on a dockerfile with node:lts-alpine3.17 and adding inotify-tools.

I'm using Docker for Windows.

I'm using the PostCreateCommand in devcontainer.json to npm install parcel as a dev dependency and bootstrap.

In my package.json file I've temporarily removed parcel from the scripts > start option, so I just have sh ../../updateme.sh to match where the wget command in the docker container put the file.

'npm start' works and the terminal reports that Debug mode is enabled and that Watches have been established.

However, even though I've updated the 'PATH_TO_WATCH' attribute in updateme.sh to the root folder of my project, it only detects changes and additions in this root folder, not any sub folders.   
e.g., PATH_TO_WATCH="/workspaces/my_cloned_git_folder"

You might be thinking I can just add '/src' to the end of the above path, but this doesn't work at all.  It says Watches have been established but it won't detect any changes to files in this sub folder, unlike when tested in the parent folder.

I haven't changed 'FILES_TO_EXCLUDE', this is still set to "(\.git|.log|.md|.lock|.json.gz)".  If I remove this I oddly get an error 'No files specified to watch!'.

Any pointers with this would be appreciated.

Many thanks
Justin

**Comment by gdi3d** [comment]
Hey, I haven't been using this for a while now. Never tried on windows, so my best guess is that it might have to be related to that.
